# Site settings
title: myBot.space
email: info@myBot.space
url: http://mybot.space
description: "myBot.space connects people with gaming robots around the world. A games platform with a difference. It's free to play but people can win real money or earn money by connecting your own robot."
skills: "Online Remote Controlled Robot Gaming Platform" 
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Drew P Robertson
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dirtybeachtv
  - title: facebook
    url: https://www.facebook.com/thebeachpartyTV/
  - title: instagram
    url: https://www.instagram.com/dirtybeach/
  - title: github
    url: http://github.com/dirtybeach

# Postal address (add as many lines as necessary)
address:
  - line: London
  - line: UK

# Credits content
credits: 'MyBot.space is a free to use, open source development platform for real world gamification... <a href="http://mybot.space">   Sign In</a>.'

# Build settings
markdown: kramdown
permalink: pretty
